version: 2.1 
orbs:
  snyk: snyk/snyk@0.0.12
jobs:
  build:
    docker:
      - image: 'circleci/node:4.8.2'
    steps:
      - checkout
      - run: npm install
      - snyk/scan:
          token-variable: SNYK_KEY	
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: medium 
      

      

